### ISSUE TITLE
"Runtime.HandlerNotFound: main.handler is undefined or not exported" after upgrade to v51

### ISSUE THREAD

**Issue by nicolaschambrier** [DataDog/datadog-lambda-extension#182]
We use docker-based lambdas, using runtime NodeJS18 (base image `public.ecr.aws/lambda/nodejs:18`), with Datadog extension installed this way:

```
COPY --from=public.ecr.aws/datadog/lambda-extension:50 /opt/extensions/ /opt/extensions
```

After switching to v51 by just changing the `50` into `51` without any other change, our lambdas stopped working with following error:

```
2023-11-28T12:16:55.666Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.HandlerNotFound",
    "errorMessage": "main.handler is undefined or not exported",
    "stack": [
        "Runtime.HandlerNotFound: main.handler is undefined or not exported",
        "    at HandlerNotFound.ExtendedError [as constructor] (/var/task/node_modules/datadog-lambda-js/dist/runtime/errors.js:113:28)",
        "    at new HandlerNotFound (/var/task/node_modules/datadog-lambda-js/dist/runtime/errors.js:131:42)",
        "    at loadSync (/var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js:377:15)",
        "    at Object.<anonymous> (/var/task/node_modules/datadog-lambda-js/dist/handler.js:35:27)",
        "    at Module._compile (node:internal/modules/cjs/loader:1256:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1119:32)",
        "    at Module._load (node:internal/modules/cjs/loader:960:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1143:19)",
        "    at require (node:internal/modules/cjs/helpers:119:18)"
    ]
}
```

Do we have to do something else to make it work? We also use (and import) `datadog-lambda-js` v7.99.0

**Comment by nicolaschambrier** [comment]
Nevermind, it was a breaking change introduced by a minor upgrade of nx (as usual) that was breaking our build.
